# vyos-router.conf - NEXWARDEN Lab
# Auteur : Alexandre Dossoukpevi | 2024
# Architecture : DMZ / Core Banking / SOC / Admin

system {
    host-name NEXWARDEN-GW
    domain-name nexwarden.lab
    time-zone Africa/Porto-Novo
}

interfaces {
    ethernet eth0 { description "WAN"; address dhcp }
    ethernet eth1 { description "DMZ 192.168.10.0/24"; address 192.168.10.1/24 }
    ethernet eth2 { description "Core Banking 192.168.20.0/24"; address 192.168.20.1/24 }
    ethernet eth3 { description "SOC 192.168.30.0/24"; address 192.168.30.1/24 }
    ethernet eth4 { description "Admin 192.168.40.0/24"; address 192.168.40.1/24 }
}

nat {
    source {
        rule 100 {
            outbound-interface eth0
            source { address 192.168.0.0/16 }
            translation { address masquerade }
        }
    }
}

firewall {
    name DMZ-TO-CORE {
        default-action drop
        rule 10 { action accept; state { established enable; related enable } }
    }
    name CORE-TO-SOC {
        default-action drop
        rule 10 { action accept; destination { port 514,5044,9200 } }
    }
}

zone-policy {
    zone DMZ   { interface eth1 }
    zone CORE  { interface eth2; from DMZ { firewall { name DMZ-TO-CORE } } }
    zone SOC   { interface eth3; from CORE { firewall { name CORE-TO-SOC } } }
    zone ADMIN { interface eth4 }
}

service {
    ssh { port 22; listen-address 192.168.40.1; disable-password-authentication }
}

protocols {
    static { route 0.0.0.0/0 { next-hop dhcp } }
}
